service: jonathan-gaQueryHandler

provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.query
    events:
      - http: GET /api/query
    environment:
      GAPI_CLIENT_EMAIL: ${file(./auth.json):client_email}
      GAPI_PRIVATE_KEY: ${file(./auth.json):private_key}